# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master 
  schedule:
    - cron: "0 9 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: fifsky/wechat-work-action@v0.0.1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      with:
        # wechat work robot webhook
        url:  https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=23a069b2-5623-4722-ab14-166f99054bce
        # message type
        type: text # optional, default is text
        # message content
        at: "曾彬"
        content: "TEST"
