name: ‘EE Action WeChat Bot’

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "11 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Run Wechat Bot Note'
      uses: fifsky/wechat-work-action@v0.0.1
      with:
        # wechat work robot webhook
        url:  https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=23a069b2-5623-4722-ab14-166f99054bce
        # message type
        type: text # optional, default is text
        # message content
        at: '曾彬'
        content: "TEST~@曾彬"
          
